server:
  port: 9000
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
  compression:
    enabled: true
    mime-types: application/json
  shutdown: graceful

spring:
  application:
    name: Account
  jackson:
    time-zone: UTC
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
      FAIL_ON_UNKNOWN_PROPERTIES: false
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
