services:
  db:
    container_name: netzfilm_08_pg_container
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=netzfilm
    ports:
      - '5432:5432'
